// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// Load all the controllers within this directory and all subdirectories.
// Controller files must be named *_controller.js.

import { Application } from "stimulus"
import { definitionsFromContext } from "stimulus/webpack-helpers"

const application = Application.start()
const context = require.context("controllers", true, /_controller\.js$/)
application.load(definitionsFromContext(context))


// import { application } from "./application"

// import BesttimeController from "./besttime_controller"
// application.register("besttime", BesttimeController)

// import CloseAlertController from "./close_alert_controller"
// application.register("close-alert", CloseAlertController)

// import HelloController from "./hello_controller"
// application.register("hello", HelloController)

// import MapboxController from "./mapbox_controller"
// application.register("mapbox", MapboxController)

// import MapdirectionController from "./mapdirection_controller"
// application.register("mapdirection", MapdirectionController)

// import RefreshListController from "./refresh_list_controller"
// application.register("refresh-list", RefreshListController)

// import ReviewsController from "./reviews_controller"
// application.register("reviews", ReviewsController)

// import SeatedAlertController from "./seated_alert_controller"
// application.register("seated-alert", SeatedAlertController)

// import SeeMapOrListButtonController from "./see_map_or_list_button_controller"
// application.register("see-map-or-list-button", SeeMapOrListButtonController)

// import ToggleFavoriteController from "./toggle_favorite_controller"
// application.register("toggle-favorite", ToggleFavoriteController)
